default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

x-local_database: &x-local-database
  adapter: postgresql
  username: xico_user
  password: x1c0p455w0rd
  host: localhost
  encoding: utf-8
  port: 5432

development:
  <<: *default
  database: xico_development
  <<: *x-local-database

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: xico_production
  <<: *x-local-database

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
